apiVersion: v1
kind: Service
metadata:
  labels:
    app: asset-generator
  name: asset-generator
spec:
  selector:
    app: asset-generator
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
